sonar.projectKey=lanacash-demo
sonar.projectName=demo (backend Spring Boot)
sonar.projectVersion=0.0.1

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Genere par mvn test (plugin jacoco-maven-plugin deja configure dans pom.xml)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8
