package com.example.demo.enums;

public enum TypeNotification {
    CONTRAT_GENERE,
    CONTRAT_SIGNE,
    DOSSIER_VALIDE,
    DOSSIER_REFUSE,
    DOCUMENT_MANQUANT,
    RELANCE_COMMERCIAL,
    DOSSIER_A_ASSIGNER,
    DOSSIER_ASSIGNE,
    DOSSIER_A_VALIDER_BOA,
    DOSSIER_RENVOYE_COMMERCIAL,
    DOSSIER_ABANDONNE,
    DOSSIER_TPE_A_AFFECTER,
    TPE_AFFECTE
}
